# Generated by Django 4.2.10 on 2024-03-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arabella', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
