# Generated by Django 4.2.10 on 2024-03-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arabella', '0002_product_delete_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
