# Generated by Django 4.2.10 on 2024-03-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arabella', '0007_alter_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='review/')),
            ],
        ),
    ]
