# Generated by Django 4.2.10 on 2024-03-20 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arabella', '0009_review_delete_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='review',
        ),
    ]
