# Generated by Django 4.2.10 on 2024-03-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arabella', '0011_fabric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='image',
            field=models.ImageField(upload_to='fabric/'),
        ),
    ]
