# Generated by Django 4.2.10 on 2024-03-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arabella', '0012_alter_fabric_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image',
        ),
    ]
