# Generated by Django 4.2.10 on 2024-03-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arabella', '0019_kids'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fabric/')),
            ],
        ),
    ]
