# Generated by Django 4.2.10 on 2024-04-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arabella', '0021_latest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
